
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.require_version ">= 1.5.0"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.hostname = "pds-virtuoso"
    config.vm.box = "ubuntu/trusty64"
    config.vm.network :private_network, ip: "192.168.33.18"
    config.vm.network "public_network"

    config.vm.provider "virtualbox" do |v|
      v.memory = 4048
      v.cpus = 2
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    end

    config.vm.provision "ansible" do |ansible|
      ansible.groups = {
        "dev" => ["default"],
        "nexus_access" => ["default"]
      }
      ansible.playbook = "vagrant.yml"
    end

end
