- hosts: default
  sudo: yes
  roles:
     - virtuoso
  vars:
    virtuoso_version: "7.2.2" # To enable newer version in VM destroy the existing machine and do new vagrant up.
    virtuoso_max_client_conns: 100
    virtuoso_thread_threshold: 100
    virtuoso_max_query_mem: 2G
    virtuoso_number_of_buffers: 300000
    virtuoso_max_dirty_buffers: 200000
